project:
  type: website
  output-dir: docs

# Métadonnées
description-meta: "Blogue sur les liens entre psychologie et intelligence artificielle"
author-meta: "Ben Plante"

website:
  title: "Benoit Plante"
  description: "Réflexions, cas d’usage et outils à l’interface entre IA et psychologie"
  site-url: "https://benoitplante.github.io/blogue"

  navbar:
    background: light

    left:
      - text: Accueil
        href: index.qmd
      - text: À propos
        href: about.qmd
      - text: Blogue
        href: posts.qmd
      - text: Thématiques
        menu:
          - text: Méthodologie augmentée
            href: posts.qmd#category=metho
          - text: Utilisation appliquée de l'IA
            href: posts.qmd#category=utilisation
          - text: Enseignement & formation
            href: posts.qmd#category=enseignement
          - text: Éthique, biais et transparence
            href: posts.qmd#category=ethique
      - text: Outils
        href: outils.qmd

  page-navigation: true

  page-footer:
    left: "[Ben Plante](https://github.com/benplante) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: "Blogue propulsé par [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/benplante
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true
  draft-mode: unlinked

  repo-url: https://github.com/benplante/blogue

  open-graph: true
  twitter-card: true

  google-analytics:
    tracking-id: ""  # à remplir si souhaité
    anonymize-ip: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
