---
title: "À propos"
description-meta: "Parcours, intentions et collaboration derrière le blogue Psychologie & IA"
page-navigation: false
toc: false
page-layout: full
---

## Qui suis-je ?

Je m’appelle **Benoit Plante**. Je suis coordonnateur scientifique du [GRIN – Groupe de recherche et d’intervention auprès des enfants vulnérables et négligés](https://oraprdnt.uqtr.uquebec.ca/portail/gscw031?owa_no_site=864), tuteur en psychologie à la [TELUQ](https://www.teluq.ca/) et doctorant à l’Université du Québec à Trois-Rivières.

Je m’intéresse aux usages de l’intelligence artificielle dans la recherche en psychologie. J’explore comment ces technologies peuvent soutenir les projets de recherche et les méthodes en psychologie. En parallèle, je m'intéresse à la science ouverte, l'utilisation des données secondaires et l'utilisation de R comme outil d'analyse en psychologie. 


## Pourquoi ce blogue ?

Ce blogue est un **carnet de bord personnel et professionnel**, que j'utilise pour partager les articles scientifiques les plus récents sur l'IA et la recherche en psychologue, pour documentater mes expérimentations dans l'utilisation d'outils d'IA et partager mes réflexions et apprentissages. J’y consigne ce que j’apprends et teste dans le cadre de mes projets :

Comme le blogue s'intéresse à l'IA, je produis l'ensemble du contenu  **en collaboration avec l’intelligence artificielle**, principalement via mes échanges avec ChatGPT. J’utilise ce partenariat pour réfléchir, structurer et produire les publications et le code qui est utilisées, dans une logique de co-écriture consciente et critique. Je cherche à être le plus transparent possible dans l'utilisation de l'IA dans les publications.

Ce blogue est volontairement exploratoire. J’y publie à mon rythme, sans prétention à l’exhaustivité, mais avec l’envie de contribuer à une culture de partage, de dialogue et d’expérimentation.

