---
title: "Psychologie & Intelligence artificielle"
description-meta: "Réflexions, outils et science à l’interface entre la psychologie et l’IA"
page-navigation: false
toc: false
page-layout: full

about:
  id: hero-heading
  template: trestles
  image-width: 70%
  links:
    - icon: envelope
      text: Courriel
      href: mailto:benoit.plante@uqtr.ca    
    - icon: github
      text: GitHub
      href: https://github.com/benplante
      target: _blank
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/benplante
      target: _blank
    - text: "{{< ai orcid >}} ORCID"
      href: https://orcid.org/0009-0003-5449-427X
      target: _blank

listing:
  - id: recent-posts
    contents: 
      - posts
      - posts/post-links.yml
    exclude:
      title: ""
    type: grid
    max-items: 3
    page-size: 3
    fields: [image, date, title, subtitle]
    max-description-length: 75
    sort: 
      - "date desc"
      - "title asc"
---

:::{#hero-heading}

Bienvenue sur **Psychologie & Intelligence artificielle**, un espace de réflexion, de vulgarisation et d’expérimentation où se rencontrent la psychologie et l’intelligence artificielle (générative, statistique, interactive).

Ce blogue documente mes explorations autour des usages concrets de l’IA dans la recherche et la pratique en psychologie : analyses reproductibles, outils IA, réflexions critiques. Il vise également à partager les nouveautés, ressources et avancées à l’intersection entre la psychologie et l’intelligence artificielle.

---

## Parcours

- Coordonnateur scientifique, GRIN – CEIDEF (UQTR)  
- Tuteur en psychologie, Université TÉLUQ  
- Doctorant en psychologie – intérêt pour la psychométrie, l'auto-quantification et les méthodes ouvertes

:::

## Derniers billets

Découvrez les derniers articles publiés sur le blogue, ou explorez les [billets par thématique](posts.qmd).

:::{#recent-posts}
:::

<p align="right">👉 [Tous les billets »](/posts.qmd)</p>
